analyzer:
  exclude:
    - "1_types/3_collections/17_sozdizimi.dart"
    - "1_types/3_collections/18_sozdizimi.dart"
    - "1_types/3_collections/19_sozdizimi.dart"
    - "1_types/3_collections/20_sozdizimi.dart"
    - "1_types/3_collections/21_sozdizimi.dart"
    - "1_types/3_collections/22_sozdizimi.dart"
    - "1_types/3_collections/25_sozdizimi.dart"
    - "1_types/3_collections/27_sozdizimi.dart"
    - "1_types/3_collections/28_sozdizimi.dart"
    - "1_types/3_collections/29_code_sample.dart"
    - "1_types/3_collections/31_sozdizimi.dart"
    - "1_types/3_collections/32_sozdizimi.dart"
    - "1_types/3_collections/33_sozdizimi.dart"
    - "1_types/3_collections/34_sozdizimi.dart"
    - "1_types/3_collections/43_sozdizimi.dart"
    - "1_types/3_collections/44_sozdizimi.dart"
    - "1_types/4_generics/01_ornek.dart"
    - "1_types/4_generics/13_ornek.dart"
    - "1_types/6_type_system/01_opening_example.dart"
    - "1_types/6_type_system/05_honeybadger.dart"
    - "1_types/6_type_system/08_chase_mouse.dart"
    - "1_types/6_type_system/10_invalid_dynamic_list.dart"
    - "1_types/6_type_system/16_local_var_type_inference_error.dart"
    - "1_types/6_type_system/21_ornek.dart"
    - "1_types/6_type_system/24_mainecoon_cat_err.dart"
    - "1_types/6_type_system/27_generic_type_assignment_animal.dart"
    - "2_patterns/2_pattern_types/02_logical_and.dart"
    - "3_control_flow/2_branches/06_ornek.dart"
    - "3_control_flow/2_branches/09_exh_bool.dart"
    - "3_control_flow/2_branches/11_ornek.dart"
    - "4_functions/1_functions/19_ornek.dart"
    - "4_functions/1_functions/26_bad_example.dart"
